var qs = require("querystring");
var url = require("url");
var u = "https://www.baidu.com/index.php?tn=56060048_4_pg&ch=12";
var uObj = url.parse(u);
var query = uObj.query;
var qObj = qs.parse(query);
qObj.ch = "88";
var querystr = qs.stringify(qObj);
uObj.search = '?'+querystr;
uObj.query = querystr;
console.log(url.format(uObj));