const qs = require('querystring');
var url = require('url');
var u = "https://user:pass@sub.host.com:8080/p/a/t/h?query=string#hash";
var uobj = url.parse(u);
var ustr = uobj.query;
var qsobj=qs.parse(ustr);
qsobj.query="hello";
var ur = qs.stringify(qsobj);
uobj.search="?"+ur;
uobj.qs=ur;
console.log(url.format(uobj));